packages:
  - './e-aesgcm'
  - './e-exe'
  - './e-gpgme'
  - './e'

extra-deps:
 - h-gpgme-0.5.0.0
 - bindings-gpgme-0.1.7

flags: {}
extra-package-dbs: []
ghc-options:
  "$locals": -fhide-source-paths

resolver: lts-12.1

allow-newer: true
