compiler: ghc-8.2.1.20170929
compiler-check: match-exact
resolver: nightly-2017-09-13

packages:
  - .
  - ../e/
  - ../e-aesgcm/
  - ../e-gpgme/

extra-deps:
  - h-gpgme-0.4.0.0
  - bindings-gpgme-0.1.7

flags: {}
extra-package-dbs: []

setup-info:
  ghc:
    linux64:
      8.2.1.20170929:
        url: https://downloads.haskell.org/~ghc/8.2.2-rc1/ghc-8.2.1.20170929-x86_64-deb8-linux.tar.xz
        content-length: 128418840
        sha1: cd2905fcf3a1f40023ab956351bd2028464b09d1
    macosx:
      8.2.1.20170929:
        url: https://downloads.haskell.org/~ghc/8.2.2-rc1/ghc-8.2.1.20170929-x86_64-apple-darwin.tar.xz
        content-length: 115407160
        sha1: 9ef2b8aeec92152fbd17dfeda877fc921422d099
