packages:
  - .
  - ../e/
  - ../e-aesgcm/
  - ../e-gpgme/

extra-deps:
  - h-gpgme-0.4.0.0
  - bindings-gpgme-0.1.7
flags: {}
extra-package-dbs: []
ghc-options:
  "$locals": -fhide-source-paths

resolver: lts-10.0
